import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
async function reveal(page,id){await page.locator(id).evaluate(el=>{for(let p=el.parentElement;p;p=p.parentElement)if(p.tagName==='DETAILS')p.open=true;});}
async function project(page){const pending=page.waitForEvent('download');await page.locator('#save').click();return JSON.parse(await readFile(await(await pending).path(),'utf8'));}
async function text(page,value){await page.locator('#textArt').click();await page.locator('#artText').fill(value);await page.locator('#insertText').click();}
test('text art, layers, transforms, manager, hero picker, snapshots and autosave',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await text(page,'HELLO\nWORLD');
 let d=await project(page);expect(d.art).toHaveLength(10);
 await reveal(page,'#layerHide');await page.locator('#layerHide').click();await expect(page.locator('#exportStats')).toContainText('Dota art categories: 0');await page.locator('#layerHide').click();
 await reveal(page,'#selectArtAll');await page.locator('#selectArtAll').click();await page.locator('#duplicateArt').click();expect((await project(page)).art).toHaveLength(20);await page.locator('#undo').click();expect((await project(page)).art).toHaveLength(10);
 await reveal(page,'#boardDuplicate');await page.locator('#boardDuplicate').click();await expect(page.locator('#boardList option')).toHaveCount(2);await page.locator('#name').fill('Second');await page.locator('#name').blur();await page.locator('#boardList').selectOption({index:0});await expect(page.locator('#name')).toHaveValue('My grid');expect((await project(page)).art).toHaveLength(10);
 await page.locator('#heroPicker').click();await page.locator('#heroSearch').fill('Axe');await page.locator('.heroCard').filter({hasText:'Axe'}).click();await page.locator('#heroDone').click();expect((await project(page)).categories[0].hero_ids).toEqual([2]);
 await reveal(page,'#saveSnapshot');await page.locator('#saveSnapshot').click();await expect(page.locator('#snapshotList option')).toHaveCount(1);await expect(page.locator('#autosaveStatus')).toContainText('Autosave:',{timeout:5000});await page.waitForFunction(()=>document.getElementById('autosaveStatus').textContent!=='Autosave: ожидание');await page.reload();await expect(page.locator('#message')).toContainText('автосохранение');expect((await project(page)).art).toHaveLength(10);expect(errors).toEqual([]);
});
test('Canvas strokes, regions, SVG conversion, compare and simple mode',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await page.locator('#fit').click();await page.locator('#drawTool').selectOption('line');const b=await page.locator('#canvas').boundingBox();await page.mouse.move(b.x+b.width*.35,b.y+b.height*.45);await page.mouse.down();await page.mouse.move(b.x+b.width*.6,b.y+b.height*.55,{steps:4});await page.mouse.up();expect((await project(page)).art.length).toBeGreaterThan(2);
 await page.locator('#drawTool').selectOption('region');await page.mouse.move(b.x+b.width*.4,b.y+b.height*.4);await page.mouse.down();await page.mouse.move(b.x+b.width*.6,b.y+b.height*.6);await page.mouse.up();expect((await project(page)).regions).toHaveLength(1);
 const svg='<svg xmlns="http://www.w3.org/2000/svg" width="80" height="80"><script>window.injected=true</script><rect width="80" height="80" fill="white"/><circle cx="40" cy="40" r="25" fill="black"/></svg>';
 const sanitized=await page.evaluate(async()=>{const {sanitizeSvg}=await import('/src/svg.mjs');return sanitizeSvg('<svg xmlns="http://www.w3.org/2000/svg" width="2800" height="1400"><rect width="2800" height="1400"/></svg>');});expect(sanitized).toContain('viewBox="0 0 2800 1400"');
 await page.locator('#imageInput').setInputFiles({name:'probe.svg',mimeType:'image/svg+xml',buffer:Buffer.from(svg)});await expect(page.locator('#imageInfo')).toContainText('probe.svg');await page.locator('#mode').selectOption('pixel');await page.locator('#convert').click();await expect(page.locator('#message')).toContainText('Создано');expect(await page.evaluate(()=>window.injected)).toBeUndefined();
 await reveal(page,'#captureCompare');await page.locator('#captureCompare').click();await text(page,'COMPARE');await page.locator('#compareToggle').click();await expect(page.locator('#compareStats')).toContainText('categories');await page.locator('#uiMode').click();await expect(page.locator('#drawTool')).toBeHidden();await page.locator('#previewMode').selectOption('dota');await page.screenshot({path:'test-results/simple-mode.png',fullPage:true});expect(errors).toEqual([]);
});
test('damaged JSON recovery and Test Install native payload',async({page})=>{
 await page.addInitScript(()=>{window.calls=[];window.__TAURI__={core:{invoke:async(cmd,args)=>{window.calls.push({cmd,args});if(cmd==='find_accounts')return[{account:'123',path:'C:/Steam/userdata/123/570/remote/cfg/hero_grid_config.json',exists:true}];if(cmd==='install_grid')return{name:'DHGS TEST',categories:args.grid.categories.length,backup:'grid-test.json'};if(cmd==='health_check')return ['Steam','Dota','Account','CFG','JSON','Backup','Write Access'].map(name=>({name,ok:true,detail:'test'}));return[];}}};});
 await page.goto('/');const valid={config_name:'Salvaged',categories:[{category_name:'OK',x_position:10,y_position:10,width:0,height:0,hero_ids:[]}]};await page.locator('#fileInput').setInputFiles({name:'damaged.json',mimeType:'application/json',buffer:Buffer.from('{"configs":['+JSON.stringify(valid)+',')});await expect(page.locator('#recoveryInfo')).toContainText('сеток: 1');await page.locator('#recoverOpen').click();await expect(page.locator('#name')).toHaveValue('Salvaged');await page.locator('#refreshAccounts').click();await page.locator('#account').selectOption({index:1});await page.locator('#testInstall').click();await expect(page.locator('#message')).toContainText('DHGS TEST обновлена');await page.locator('#testInstall').click();const calls=await page.evaluate(()=>window.calls.filter(c=>c.cmd==='install_grid'));expect(calls).toHaveLength(2);expect(calls.every(c=>c.args.test===true)).toBeTruthy();await page.locator('#healthCheck').click();await expect(page.locator('.healthRow')).toHaveCount(7);
});
