import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { artToDotaCategories, buildArtExport, calibrationConfig, enforceBudget, isTextCategory, textCategory } from '../src/art-export.mjs';
import { currentConfig, exportDota, importDota, newDocument, parseDota, parseProject, projectJSON } from '../src/core.mjs';
import { convertPixels, tangentGlyph } from '../src/converter.mjs';
import { fontCoverage } from '../src/font.mjs';
const glyph=(symbol,x,y=20,size=12)=>({symbol,x,y,size});
test('one symbol becomes a native empty Dota category without invented fields',()=>assert.deepEqual(artToDotaCategories([glyph('#',10)]),[textCategory('#',10,20)]));
test('per glyph keeps coordinates, Unicode and fractional positions',()=>assert.deepEqual(artToDotaCategories([glyph('█',1.25),glyph('─',9.5)],{mode:'glyph',asciiFallback:false}),[textCategory('█',1.25,20),textCategory('─',9.5,20)]));
test('compatible row runs combine and leave gaps untouched',()=>assert.deepEqual(artToDotaCategories([glyph('A',0),glyph('B',8),glyph('C',24)]),[textCategory('AB',0,20),textCategory('C',24,20)]));
test('Auto falls back when spacing does not fit',()=>assert.equal(artToDotaCategories([glyph('A',0),glyph('B',11)]).length,2));
test('different rows and sizes never merge',()=>assert.equal(artToDotaCategories([glyph('A',0),glyph('B',8,21),glyph('C',8,20,13)]).length,3));
test('row quantization does not bridge stair steps',()=>assert.equal(artToDotaCategories([glyph('A',0,20),glyph('B',8,20.1)]).length,2));
test('calibrated variable glyph advances are used',()=>assert.equal(artToDotaCategories([glyph('i',0),glyph('W',3),glyph('i',13)],{advanceByGlyph:{i:3,W:10}})[0].category_name,'iWi'));
test('runs are capped at the configured length',()=>assert.equal(artToDotaCategories(Array.from({length:8},(_,i)=>glyph('#',8*i)),{maxRunLength:3}).length,3));
test('unsupported glyphs fall back and report count',()=>{const r=buildArtExport([glyph('╱',0),glyph('█',8)],{supportedGlyphs:['/','#']});assert.equal(r.categories[0].category_name,'/#');assert.equal(r.fallbackCount,2);});
test('unavailable fallback is an explicit error',()=>assert.throws(()=>artToDotaCategories([glyph('█',0)],{supportedGlyphs:['A']}),/fallback/));
test('disabled export leaves editor objects untouched',()=>{const art=[glyph('#',0)];assert.deepEqual(artToDotaCategories(art,{enabled:false}),[]);assert.equal(art.length,1);});
test('calibration applies coordinates only, never font size',()=>assert.deepEqual(artToDotaCategories([glyph('A',10,20,99)],{horizontalSpacing:2,verticalSpacing:3,preserveAspect:false,xOffset:1,yOffset:2,baselineOffset:4}),[textCategory('A',21,66)]));
test('budget prevents output, never silently drops categories',()=>{const d=newDocument();d.categories=[textCategory('original',0,0)];d.art=[glyph('A',0),glyph('B',20)];d.exportSettings.budget=2;assert.throws(()=>exportDota(d),/3.*2/);assert.equal(d.art.length,2);assert.throws(()=>enforceBudget(10001,{budget:10000}));});
test('native heroes and generated text coexist',()=>{const d=newDocument();d.categories=[{...textCategory('Carry',0,0),width:200,height:100,hero_ids:[1,2]}];d.art=[glyph('#',20)];const c=currentConfig(d);assert.equal(c.categories.length,2);assert.deepEqual(c.categories[0].hero_ids,[1,2]);assert.ok(isTextCategory(c.categories[1]));});
test('text probe JSON round trip preserves every field and label',()=>{const data=readFileSync(new URL('../fixtures/text_category_probe.json',import.meta.url),'utf8');assert.deepEqual(exportDota(importDota(data)),parseDota(data));});
test('edited config and root unknown fields survive',()=>{const root={version:3,rootExtra:'x',configs:[{config_name:'X',extra:{a:1},categories:[{...textCategory('#',3,4),unknown:42}]}]};assert.deepEqual(exportDota(importDota(JSON.stringify(root))),root);});
test('old projects migrate without losing art',()=>{const d=newDocument();d.formatVersion=1;delete d.exportSettings;d.art=[glyph('#',0)];const p=parseProject(JSON.stringify(d));assert.equal(p.formatVersion,2);assert.equal(currentConfig(p).categories.length,1);});
test('invalid art and export options fail with readable errors',()=>{assert.throws(()=>artToDotaCategories([glyph('#',NaN)]),/art\[0\].x/);assert.throws(()=>artToDotaCategories([],{mode:'fake'}),/mode/);assert.throws(()=>artToDotaCategories([],{budget:0}),/budget/);const d=newDocument();d.art=[glyph('#','10')];assert.throws(()=>parseProject(projectJSON(d)),/finite/);});
test('calibration includes labels, blocks, rows, and no fake fields',()=>{const c=calibrationConfig();assert.ok(c.categories.some(x=>x.category_name==='█'));assert.ok(c.categories.every(isTextCategory));assert.deepEqual(parseDota(JSON.stringify({version:3,configs:[c]})).configs[0],c);});
test('tangent glyphs follow image-space gradient direction',()=>{assert.equal(tangentGlyph(0),'│');assert.equal(tangentGlyph(Math.PI/2),'─');assert.equal(tangentGlyph(Math.PI/4),'╱');assert.equal(tangentGlyph(-Math.PI/4),'╲');});
test('large art export remains bounded and optimizes rows',()=>{const art=Array.from({length:10000},(_,i)=>glyph('#',i%100*8,Math.floor(i/100)*16));const r=buildArtExport(art);assert.equal(r.categories.length,200);assert.equal(r.reduction,98);});
test('line and ASCII conversion export actual image-derived text',()=>{const px=new Uint8ClampedArray(32*32*4);for(let y=0;y<32;y++)for(let x=0;x<32;x++){const i=(y*32+x)*4,v=x>10&&x<22&&y>5&&y<27?0:255;px.set([v,v,v,255],i);}for(const mode of ['line','ascii','silhouette','dither']){const d=newDocument();d.art=convertPixels(px,32,32,{mode,columns:24,rows:24,blur:0,threshold:40,noise:0});assert.ok(d.art.length>0);assert.ok(currentConfig(d).categories.length>0);}});
test('font parser rejects malformed data instead of trusting fallback measurements',()=>assert.throws(()=>fontCoverage(new ArrayBuffer(12)),/TTF/));
test('Unicode cmap format 12 identifies missing glyphs',()=>{const b=new ArrayBuffer(68),v=new DataView(b);v.setUint32(0,0x10000);v.setUint16(4,1);v.setUint32(12,0x636d6170);v.setUint32(20,28);v.setUint32(24,40);v.setUint16(30,1);v.setUint16(32,3);v.setUint16(34,10);v.setUint32(36,12);v.setUint16(40,12);v.setUint32(44,28);v.setUint32(52,1);v.setUint32(56,65);v.setUint32(60,66);v.setUint32(64,1);const has=fontCoverage(b);assert.ok(has('A'));assert.ok(has('B'));assert.equal(has('C'),false);});
